### ISSUE TITLE
Check on RHEL 7.6 fails

### ISSUE THREAD

**Issue by jucaf** [IBM-ICP4D/icp4d-serviceability-cli#1]
Documentation for icp4d 2.1.x requires RHEL 7.5 or greater, but check fails on RHEL 7.6 and versions lower than 7.5 doesn't cause error.

**Comment by sachinadams** [comment]
Yes, we will fix that with an update soon. Thanks for pointing it out.

**Comment by sachinadams** [comment]
Change delivered.

**Comment by jucaf** [comment]
Thanks for not accepting my PR and change the code by yourself. First and last collaboration in this project.
